version: '3'
services:
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - ${PWD}/data/postgres:/var/lib/postgresql/data
    ports:
      - 5438:5432
    networks:
      - enterprise-bitcoin-network
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDB}

  bitcoind:
    image: bitcoind
    container_name: bitcoind
    build: bitcoind
    volumes:
      - ${PWD}/data/bitcoind:/root/.bitcoin
    command: /bin/bash -c "cd /bitcoin && src/bitcoind -txindex -dbcache=10000"
    restart: always
    depends_on:
      - postgres
    networks:
      - enterprise-bitcoin-network
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDB=${PGDB}

  tweeter:
    image: tweeter
    container_name: tweeter
    build:
      context: ${PWD}/tweeter/
      dockerfile: ${PWD}/tweeter/Dockerfile
      args:
        - BUILD_VERSION
    entrypoint: [ "./start-tweeter.sh" ]
    networks:
      - enterprise-bitcoin-network

networks:
  enterprise-bitcoin-network:
    driver: bridge